## What you will do:
- Read data into a pandas data frame
- Explore the dataset
- Split the data into training and test set
- Create a machine learning model
- Train the model and make predictions

## The scenario/task
The data comprises students achievement in secondary education of two Portuguese schools. The features/attributes include student grades, demographic, social and school related features. Initially, data was collected using school reports and questionnaires. The dataset we are concerned with regards Maths subject. The target attribute `G3` has a strong correlation with attributes `G2` and `G1`. This occurs because G3 is the final year grade, while G1 and G2 correspond to the 1st and 2nd period grades. It would be a challenge to predict G3 without G2 and G1.

## Import the libraries
- pandas, numpy, sklearn, seaborn

In [3]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import linear_model
import seaborn as sns

## Task 1:
- Load the file students-mat.csv using pandas. Note that it is a comma separated file
- To load read the file:
  - upload it to google  drive first
  - then read it using appropriate pandas method - place it in a dataframe called `dataframe` or any other variable name of your choice

In [6]:
df = pd.read_csv('students-mat.csv', sep = ';')
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

## Task 2 - inspecting the data
- review the first 5 records in the dataset
- review the last 5 records in the dataset
Review the column properties so you can tell what their data types are.<br>
<b>Question</b>:
How many records are in your dataset? How many columns/features does each instance have?

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

33

## Task 3 - Feature selection 
- we want to work with a few features, namely - `"G1", "G2", "G3", "studytime", "failures", "absences"`.
- create a new dataframe with these features, either use a different variable name or same varible name (dataframe)

### check the first 5 records of the new dataframe

In [7]:
features = ["G1", "G2", "studytime", "failures", "absences"]

X = df[features]

y = df['G3']

X.shape

## Task 4 - Preparing data for ML
- Create two arrays, one for target, and one for the other features
- Target is 'G3'

- place your features in a variable x and your target in variable y
## How to do it:
  - drop target from the main dataframe and assign the remaining features to x
  - assign y to G3.

  NB: both x and y should be numpy arrays. <br>
Check the shape of both x and y

## Task 5 - Spllitting data into training and testing datasets
- import the train_test_split function from sklearn.model_selection
- use appropriate array names (e.g.,  What is x_train, x_test, y_train, y_test) to split your features. Keep 90% of your data for training

## Creating a ML model
- import the linear regression model from sklearn
- create a model instance...call it linearM
## Training the model
- Train your model with your training dataset
- Make predictions using the test dataset
- Print out what the model has predicted, values of test set, and the values y_test...something like this:
 for x in range(len(predictions)):
    print(predictions[x], x_test[x], y_test[x])

## Task 6 - Check accuracy
- to do this, use the score function of your model(linearM) as follows:
linearM.score(xtest, ytest)

## Task 7 - Training  a model multiple times

- We will do this together